apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: yourdockerhubusername/static-website:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: NodePort
  selector:
    app: static-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
