apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  labels:
    app: static-website
spec:
  type: NodePort
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
